libdxfrw: avoid alignment errors in dxfreader.cpp
Reinterpret_cast is only allowable if the from type satisfies the alignment
requirement of the target. Using GCC 15.2 on RISC-V the current code of
dxfreader leads to errors like

    dxfreader.cpp:121:14: error: cast from ‘char*’ to ‘short unsigned int*’
    increases required alignment of target type [-Werror=cast-align]

We can avoid reinterpret_cast by using unions.

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>