vposter: avoid illegal reinterpret_cast
A reinterpret_cast where the target has a higher alignment requirement
than the source leads to an error as observed with GCC 15.2 on riscv64:

    vposter.cpp:73:30: error:
    cast from ‘uchar*’ {aka ‘unsigned char*’} to ‘QRgb*’
    {aka ‘unsigned int*’} increases required alignment of target type
    [-Werror=cast-align]

As we know that QImage::scanLine() returns 32bit aligned data
use an unsafe conversion via a void * pointer instead.

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>